// map.js — world generation & access
import { TILE } from './utils.js'

export const MAP_COLS = 120
export const MAP_ROWS = 160

export function newMap() {
  const m = []
  for (let r=0;r<MAP_ROWS;r++) {
    const row = []
    for (let c=0;c<MAP_COLS;c++) {
      if (r > MAP_ROWS-6) row.push(1)
      else if (r===MAP_ROWS-7 && Math.random()<0.02) row.push(3)
      else if (Math.random()<0.006 && r>5) row.push(2)
      else row.push(0)
    }
    m.push(row)
  }
  return m
}

export function getTile(m,r,c){ if(r<0||c<0||r>=MAP_ROWS||c>=MAP_COLS) return 0; return m[r][c] }
export function setTile(m,r,c,v){ if(r<0||c<0||r>=MAP_ROWS||c>=MAP_COLS) return; m[r][c]=v }
// map docs — documentation line 1
// map docs — documentation line 2
// map docs — documentation line 3
// map docs — documentation line 4
// map docs — documentation line 5
// map docs — documentation line 6
// map docs — documentation line 7
// map docs — documentation line 8
// map docs — documentation line 9
// map docs — documentation line 10
// map docs — documentation line 11
// map docs — documentation line 12
// map docs — documentation line 13
// map docs — documentation line 14
// map docs — documentation line 15
// map docs — documentation line 16
// map docs — documentation line 17
// map docs — documentation line 18
// map docs — documentation line 19
// map docs — documentation line 20
// map docs — documentation line 21
// map docs — documentation line 22
// map docs — documentation line 23
// map docs — documentation line 24
// map docs — documentation line 25
// map docs — documentation line 26
// map docs — documentation line 27
// map docs — documentation line 28
// map docs — documentation line 29
// map docs — documentation line 30
// map docs — documentation line 31
// map docs — documentation line 32
// map docs — documentation line 33
// map docs — documentation line 34
// map docs — documentation line 35
// map docs — documentation line 36
// map docs — documentation line 37
// map docs — documentation line 38
// map docs — documentation line 39
// map docs — documentation line 40
// map docs — documentation line 41
// map docs — documentation line 42
// map docs — documentation line 43
// map docs — documentation line 44
// map docs — documentation line 45
// map docs — documentation line 46
// map docs — documentation line 47
// map docs — documentation line 48
// map docs — documentation line 49
// map docs — documentation line 50
// map docs — documentation line 51
// map docs — documentation line 52
// map docs — documentation line 53
// map docs — documentation line 54
// map docs — documentation line 55
// map docs — documentation line 56
// map docs — documentation line 57
// map docs — documentation line 58
// map docs — documentation line 59
// map docs — documentation line 60
// map docs — documentation line 61
// map docs — documentation line 62
// map docs — documentation line 63
// map docs — documentation line 64
// map docs — documentation line 65
// map docs — documentation line 66
// map docs — documentation line 67
// map docs — documentation line 68
// map docs — documentation line 69
// map docs — documentation line 70
// map docs — documentation line 71
// map docs — documentation line 72
// map docs — documentation line 73
// map docs — documentation line 74
// map docs — documentation line 75
// map docs — documentation line 76
// map docs — documentation line 77
// map docs — documentation line 78
// map docs — documentation line 79
// map docs — documentation line 80
// map docs — documentation line 81
// map docs — documentation line 82
// map docs — documentation line 83
// map docs — documentation line 84
// map docs — documentation line 85
// map docs — documentation line 86
// map docs — documentation line 87
// map docs — documentation line 88
// map docs — documentation line 89
// map docs — documentation line 90
// map docs — documentation line 91
// map docs — documentation line 92
// map docs — documentation line 93
// map docs — documentation line 94
// map docs — documentation line 95
// map docs — documentation line 96
// map docs — documentation line 97
// map docs — documentation line 98
// map docs — documentation line 99
// map docs — documentation line 100
// map docs — documentation line 101
// map docs — documentation line 102
// map docs — documentation line 103
// map docs — documentation line 104
// map docs — documentation line 105
// map docs — documentation line 106
// map docs — documentation line 107
// map docs — documentation line 108
// map docs — documentation line 109
// map docs — documentation line 110
// map docs — documentation line 111
// map docs — documentation line 112
// map docs — documentation line 113
// map docs — documentation line 114
// map docs — documentation line 115
// map docs — documentation line 116
// map docs — documentation line 117
// map docs — documentation line 118
// map docs — documentation line 119
// map docs — documentation line 120
// map docs — documentation line 121
// map docs — documentation line 122
// map docs — documentation line 123
// map docs — documentation line 124
// map docs — documentation line 125
// map docs — documentation line 126
// map docs — documentation line 127
// map docs — documentation line 128
// map docs — documentation line 129
// map docs — documentation line 130
// map docs — documentation line 131
// map docs — documentation line 132
// map docs — documentation line 133
// map docs — documentation line 134
// map docs — documentation line 135
// map docs — documentation line 136
// map docs — documentation line 137
// map docs — documentation line 138
// map docs — documentation line 139
// map docs — documentation line 140
// map docs — documentation line 141
// map docs — documentation line 142
// map docs — documentation line 143
// map docs — documentation line 144
// map docs — documentation line 145
// map docs — documentation line 146
// map docs — documentation line 147
// map docs — documentation line 148
// map docs — documentation line 149
// map docs — documentation line 150
// map docs — documentation line 151
// map docs — documentation line 152
// map docs — documentation line 153
// map docs — documentation line 154
// map docs — documentation line 155
// map docs — documentation line 156
// map docs — documentation line 157
// map docs — documentation line 158
// map docs — documentation line 159
// map docs — documentation line 160
// map docs — documentation line 161
// map docs — documentation line 162
// map docs — documentation line 163
// map docs — documentation line 164
// map docs — documentation line 165
// map docs — documentation line 166
// map docs — documentation line 167
// map docs — documentation line 168
// map docs — documentation line 169
// map docs — documentation line 170
// map docs — documentation line 171
// map docs — documentation line 172
// map docs — documentation line 173
// map docs — documentation line 174
// map docs — documentation line 175
// map docs — documentation line 176
// map docs — documentation line 177
// map docs — documentation line 178
// map docs — documentation line 179
// map docs — documentation line 180
// map docs — documentation line 181
// map docs — documentation line 182
// map docs — documentation line 183
// map docs — documentation line 184
// map docs — documentation line 185
// map docs — documentation line 186
// map docs — documentation line 187
// map docs — documentation line 188
// map docs — documentation line 189
// map docs — documentation line 190
// map docs — documentation line 191
// map docs — documentation line 192
// map docs — documentation line 193
// map docs — documentation line 194
// map docs — documentation line 195
// map docs — documentation line 196
// map docs — documentation line 197
// map docs — documentation line 198
// map docs — documentation line 199
// map docs — documentation line 200
// map docs — documentation line 201
// map docs — documentation line 202
// map docs — documentation line 203
// map docs — documentation line 204
// map docs — documentation line 205
// map docs — documentation line 206
// map docs — documentation line 207
// map docs — documentation line 208
// map docs — documentation line 209
// map docs — documentation line 210
// map docs — documentation line 211
// map docs — documentation line 212
// map docs — documentation line 213
// map docs — documentation line 214
// map docs — documentation line 215
// map docs — documentation line 216
// map docs — documentation line 217
// map docs — documentation line 218
// map docs — documentation line 219
// map docs — documentation line 220
// map docs — documentation line 221
// map docs — documentation line 222
// map docs — documentation line 223
// map docs — documentation line 224
// map docs — documentation line 225
// map docs — documentation line 226
// map docs — documentation line 227
// map docs — documentation line 228
// map docs — documentation line 229
// map docs — documentation line 230
// map docs — documentation line 231
// map docs — documentation line 232
// map docs — documentation line 233
// map docs — documentation line 234
// map docs — documentation line 235
// map docs — documentation line 236
// map docs — documentation line 237
// map docs — documentation line 238
// map docs — documentation line 239
// map docs — documentation line 240
// map docs — documentation line 241
// map docs — documentation line 242
// map docs — documentation line 243
// map docs — documentation line 244
// map docs — documentation line 245
// map docs — documentation line 246
// map docs — documentation line 247
// map docs — documentation line 248
// map docs — documentation line 249
// map docs — documentation line 250
// map docs — documentation line 251
// map docs — documentation line 252
// map docs — documentation line 253
// map docs — documentation line 254
// map docs — documentation line 255
// map docs — documentation line 256
// map docs — documentation line 257
// map docs — documentation line 258
// map docs — documentation line 259
// map docs — documentation line 260
// map docs — documentation line 261
// map docs — documentation line 262
// map docs — documentation line 263
// map docs — documentation line 264
// map docs — documentation line 265
// map docs — documentation line 266
// map docs — documentation line 267
// map docs — documentation line 268
// map docs — documentation line 269
// map docs — documentation line 270
// map docs — documentation line 271
// map docs — documentation line 272
// map docs — documentation line 273
// map docs — documentation line 274
// map docs — documentation line 275
// map docs — documentation line 276
// map docs — documentation line 277
// map docs — documentation line 278
// map docs — documentation line 279
// map docs — documentation line 280
// map docs — documentation line 281
// map docs — documentation line 282
// map docs — documentation line 283
// map docs — documentation line 284
// map docs — documentation line 285
// map docs — documentation line 286
// map docs — documentation line 287
// map docs — documentation line 288
// map docs — documentation line 289
// map docs — documentation line 290
// map docs — documentation line 291
// map docs — documentation line 292
// map docs — documentation line 293
// map docs — documentation line 294
// map docs — documentation line 295
// map docs — documentation line 296
// map docs — documentation line 297
// map docs — documentation line 298
// map docs — documentation line 299
// map docs — documentation line 300
// map docs — documentation line 301
// map docs — documentation line 302
// map docs — documentation line 303
// map docs — documentation line 304
// map docs — documentation line 305
// map docs — documentation line 306
// map docs — documentation line 307
// map docs — documentation line 308
// map docs — documentation line 309
// map docs — documentation line 310
// map docs — documentation line 311
// map docs — documentation line 312
// map docs — documentation line 313
// map docs — documentation line 314
// map docs — documentation line 315
// map docs — documentation line 316
// map docs — documentation line 317
// map docs — documentation line 318
// map docs — documentation line 319
// map docs — documentation line 320
// map docs — documentation line 321
// map docs — documentation line 322
// map docs — documentation line 323
// map docs — documentation line 324
// map docs — documentation line 325
// map docs — documentation line 326
// map docs — documentation line 327
// map docs — documentation line 328
// map docs — documentation line 329
// map docs — documentation line 330
// map docs — documentation line 331
// map docs — documentation line 332
// map docs — documentation line 333
// map docs — documentation line 334
// map docs — documentation line 335
// map docs — documentation line 336
// map docs — documentation line 337
// map docs — documentation line 338
// map docs — documentation line 339
// map docs — documentation line 340
// map docs — documentation line 341
// map docs — documentation line 342
// map docs — documentation line 343
// map docs — documentation line 344
// map docs — documentation line 345
// map docs — documentation line 346
// map docs — documentation line 347
// map docs — documentation line 348
// map docs — documentation line 349
// map docs — documentation line 350
